"""initial schema with user scoping

Revision ID: 6e636a1cba04
Revises: 
Create Date: 2026-09-19 13:01:42.950375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e636a1cba04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_reviews', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_anomaly_reviews_anomaly_signature', table_name='anomaly_reviews')
    op.create_index(op.f('ix_anomaly_reviews_anomaly_signature'), 'anomaly_reviews', ['anomaly_signature'], unique=False)
    op.create_index(op.f('ix_anomaly_reviews_user_id'), 'anomaly_reviews', ['user_id'], unique=False)
    op.create_foreign_key(None, 'anomaly_reviews', 'users', ['user_id'], ['id'])
    op.add_column('budget_goals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('budget_goals', 'monthly_cap',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index('ix_budget_goals_category', table_name='budget_goals')
    op.create_index(op.f('ix_budget_goals_category'), 'budget_goals', ['category'], unique=False)
    op.create_index(op.f('ix_budget_goals_user_id'), 'budget_goals', ['user_id'], unique=False)
    op.create_foreign_key(None, 'budget_goals', 'users', ['user_id'], ['id'])
    op.add_column('pending_receipts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_pending_receipts_user_id'), 'pending_receipts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'pending_receipts', 'users', ['user_id'], ['id'])
    op.add_column('savings_goals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('savings_goals', 'target_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_savings_goals_user_id'), 'savings_goals', ['user_id'], unique=False)
    op.create_foreign_key(None, 'savings_goals', 'users', ['user_id'], ['id'])
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('transactions', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('transactions', 'user_id')
    op.drop_constraint(None, 'savings_goals', type_='foreignkey')
    op.drop_index(op.f('ix_savings_goals_user_id'), table_name='savings_goals')
    op.alter_column('savings_goals', 'target_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('savings_goals', 'user_id')
    op.drop_constraint(None, 'pending_receipts', type_='foreignkey')
    op.drop_index(op.f('ix_pending_receipts_user_id'), table_name='pending_receipts')
    op.drop_column('pending_receipts', 'user_id')
    op.drop_constraint(None, 'budget_goals', type_='foreignkey')
    op.drop_index(op.f('ix_budget_goals_user_id'), table_name='budget_goals')
    op.drop_index(op.f('ix_budget_goals_category'), table_name='budget_goals')
    op.create_index('ix_budget_goals_category', 'budget_goals', ['category'], unique=1)
    op.alter_column('budget_goals', 'monthly_cap',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('budget_goals', 'user_id')
    op.drop_constraint(None, 'anomaly_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_anomaly_reviews_user_id'), table_name='anomaly_reviews')
    op.drop_index(op.f('ix_anomaly_reviews_anomaly_signature'), table_name='anomaly_reviews')
    op.create_index('ix_anomaly_reviews_anomaly_signature', 'anomaly_reviews', ['anomaly_signature'], unique=1)
    op.drop_column('anomaly_reviews', 'user_id')
    # ### end Alembic commands ###
